### PR TITLE
some basic changes

### PR DESCRIPTION
**Pull request by chicken-nugget1104**
would not know if you want these, however you can overlook them incase you want to merge this.

CHANGES:
- allowed usernames in singleplayer mode (i tested, there is random numbers after Player.)
- changed some stuff in core.glsl to make it a bit more "readable" and also bit better on performance
- changed the pushout block code in the update in player to be in its own function, i do not know if this runs better or not.

showcase of usernames in singleplayer:
image

### CODE REVIEW

**Comment by chicken-nugget1104** [comment]
also wrote some code for random splash texts if you want that (main menu), however i will not be pushing that to my fork.
oh that also doesn't use splashes.txt because uh, i just didn't think of that...

**Comment by SaiyanGonzalez01** [comment]
Wow, you got some stuff! Would you like me to add you to the contributors part of the README.md?

**Comment by chicken-nugget1104** [comment]
> Wow, you got some stuff! Would you like me to add you to the contributors part of the README.md?

uh yes, please.
it would only be fair!

**Comment by SaiyanGonzalez01** [comment]
Alright, i'll merge the pull request and add you to the README.md.

**Comment by chicken-nugget1104** [comment]
> Alright, i'll merge the pull request and add you to the README.md.

neato

**Pull request merged**
