### PR TITLE
MAJOR RANDOM UPDATE

### PR DESCRIPTION
**Pull request by chicken-nugget1104**
WOAH

i updated the random.java

yay
i dunno if i improved it or

### CODE REVIEW

**Comment by chicken-nugget1104** [comment]
oh also toggle the new bool if you want to enable a more "complex" version of nextint

the title screen doesnt use this varient because java.utils.random works better for that
(this doesnt work for random splash texts. dont try it.)

**Comment by SaiyanGonzalez01** [comment]
> i updated the random.java
> 
> yay i dunno if i improved it or

Isn't the random.java for seeds and generation? If you edited it, it probably made vanilla seeds  broken and not be able to be generated again. Also, what is nextint?

**Comment by chicken-nugget1104** [comment]
> > i updated the random.java
> > yay i dunno if i improved it or
> 
> Isn't the random.java for seeds and generation? If you edited it, it probably made vanilla seeds broken and not be able to be generated again. Also, what is nextint?

it is, yes, but this is basically still the same thing (also i just improved its performance so like)

also nextint is like well its in the name

**Comment by SaiyanGonzalez01** [comment]
oh alright, I will merge tomorrow

**Pull request merged**
