### PR TITLE
Printing and optimizations

### PR DESCRIPTION
**Pull request by chicken-nugget1104**
print option
disables all prints... in minecraft.java
you can add more, to disable prints basically, if you want, from all places that uses prints

but
yeah

ALSO, adds null checks too

(starts off as off by default, meaning no printing will occur, which means it will not lag due to printing!)

### CODE REVIEW

**Comment by chicken-nugget1104** [comment]
hope it works
uh
oh yeah
you can test this at: https://mineycraft.netlify.app/

**Comment by chicken-nugget1104** [comment]
@SaiyanGonzalez01 sorry for the ping again
overlook this PR when you get the chance!

also glad this fork is more active then the original 1.7.3

LOL

**Comment by SaiyanGonzalez01** [comment]
Real lol, and btw, how do usernames work? are they random or something else?

**Comment by chicken-nugget1104** [comment]
> Real lol, and btw, how do usernames work? are they random or something else?

Well, this.username comes from Session.java
however i do not know where Session.java gets the username from but it does seem random

(UPDATE: did testing on both websites, seems to always be 094 at the end. Will try and change this however, once i figure out where Session.java actually gets the username from...)

**Comment by SaiyanGonzalez01** [comment]
Alright, thanks for the info!

**Comment by chicken-nugget1104** [comment]
> Alright, thanks for the info!

writing some code to automate the search for the session thing to make truly random usernames

**Pull request merged**
