### PR TITLE
Splash text randomization

### PR DESCRIPTION
**Pull request by chicken-nugget1104**
began using my org as to make the branches, as by default i was using the original project that you forked.

this is a randomization of splash texts for the title screen, feel free to change the splashes as you see fit.

DOES NOT USE SPLASHES.TXT

### CODE REVIEW

**Comment by chicken-nugget1104** [comment]
Sorry for possibly overwhelming you with PR's

However Next PR will add an option to stop printing altogether, which can lag.

**Comment by chicken-nugget1104** [comment]
Do not mind me pinging you, this is just something i think you would want.
@SaiyanGonzalez01

**Comment by SaiyanGonzalez01** [comment]
Oh no its fine, this was something I wanted when I first made Minecraft Old-School!

**Comment by chicken-nugget1104** [comment]
> Oh no its fine, this was something I wanted when I first made Minecraft Old-School!

Ah, alright
I will be doing the print one soon, it will also add some null checks in some spots.

**Pull request merged**
