### PR TITLE
fix black textures

### PR DESCRIPTION
**Pull request by chicken-nugget1104**
uh please do merge if you wish

### CODE REVIEW

**Comment by chicken-nugget1104** [comment]
only runs ONCE, and i do believe you would want this incase you have not added a fix yourself

**Comment by chicken-nugget1104** [comment]
@SaiyanGonzalez01

**Comment by chicken-nugget1104** [comment]
oh, i also have some performance stuff that may not make a dent, but if you are interested then check out my fork, and check the performance branch.

**Comment by SaiyanGonzalez01** [comment]
You can fix the black textures by toggling 3D Anaglyph On & Off, which will show the regular textures and no black ones. (You might need to do it again and again, it doesn't for me but some commenters on Reddit say they have to!)

**Comment by SaiyanGonzalez01** [comment]
However, I would like to fix it so people don't have to do it.

**Comment by chicken-nugget1104** [comment]
> You can fix the black textures by toggling 3D Anaglyph On & Off, which will show the regular textures and no black ones. (You might need to do it again and again, it doesn't for me but some commenters on Reddit say they have to!)

i already know that, however this was a more permanent solution, without requiring the average user to do so.

**Pull request merged**
