### PR TITLE
Cloud toggle

### PR DESCRIPTION
**Pull request by chicken-nugget1104**
yeah
btw why did you completely revert all changes to minecraft.java?

### CODE REVIEW

**Comment by chicken-nugget1104** [comment]
but anyway this adds the ability to completely toggle clouds
they will NOT change position if they are off btw

**Comment by chicken-nugget1104** [comment]
@SaiyanGonzalez01 wakey wakey
this cloud toggle should update performance on chromebooks btw
should run better
cant test cuz im not going to school

**Comment by SaiyanGonzalez01** [comment]
Oh yea I reverted the Minecraft.java because it kinda crashed the game, so I just reverted it to the original untouched version

**Comment by chicken-nugget1104** [comment]
> Oh yea I reverted the Minecraft.java because it kinda crashed the game, so I just reverted it to the original untouched version

...huh?
did it actually
are you like
sure of that???
you could try and figure out a fix, or i could
but it doesnt crash for me???

like did you do something special or
@SaiyanGonzalez01

**Comment by SaiyanGonzalez01** [comment]
Yes I'm sure, it just froze and never went back to normal, even left it for an hour and it didn't load, when I reverted the Minecraft.java, it fixed.

**Comment by SaiyanGonzalez01** [comment]
Oh and weirdly, the terminal did this 

Screenshot 2024-12-05 7 37 05 PM

**Comment by SaiyanGonzalez01** [comment]
I'll fix it so it can work

**Comment by chicken-nugget1104** [comment]
> Oh and weirdly, the terminal did this
> 
> Screenshot 2024-12-05 7 37 05 PM

weird
this doesn't occur for me?

**Comment by chicken-nugget1104** [comment]
@SaiyanGonzalez01 so can tyou merge or

**Comment by chicken-nugget1104** [comment]
revert the guiingame update if it fails to compile (the newest one)
i have really not tested the spam prevention

**Comment by SaiyanGonzalez01** [comment]
alright, i'll download the current state of the project, then merge the project, so if anything breaks, I could just bring files from the .zip

**Comment by SaiyanGonzalez01** [comment]
Screenshot 2024-12-06 7 57 51 PM

Well this is the only error I got so far

**Comment by SaiyanGonzalez01** [comment]
Oh that was a simple fix I just removed the two pieces of code you wrote and reverted it to the original, but that was the only thing that I had to change to fix it, the rest of your code is fine and there.

**Comment by SaiyanGonzalez01** [comment]
Shoot its crashing again

**Pull request merged**
