### PR TITLE
OK OK last PR fr, please do merge

### PR DESCRIPTION
**Pull request by chicken-nugget1104**
it has come to my attention that my approach to saving was bad, and so i changed it.

this is... something you will definitely want.
@SaiyanGonzalez01 

last PR i will make 'til after thanksgiving i swear

### CODE REVIEW

**Comment by SaiyanGonzalez01** [comment]
alr, I'll merge this soon, and quick question, does importing saves work for you?

**Comment by chicken-nugget1104** [comment]
> alr, I'll merge this soon, and quick question, does importing saves work for you?

Importing saves?
as in importing worlds? or?

**Comment by SaiyanGonzalez01** [comment]
yea importing worlds. Tried a couple of times on vanilla beta 1.7.3, didnt work on my end

**Comment by chicken-nugget1104** [comment]
> yea importing worlds. Tried a couple of times on vanilla beta 1.7.3, didnt work on my end

havent tried it... ever

**Comment by SaiyanGonzalez01** [comment]
well maybe its just my computer that's just freezing the game everytime it tries to import

**Pull request merged**
