### PR TITLE
USERNAME SETTING

### PR DESCRIPTION
**Pull request by chicken-nugget1104**
THIS TOOK SO LONG OF SEARCHING

### CODE REVIEW

**Comment by chicken-nugget1104** [comment]
@SaiyanGonzalez01 you wanted to know how usernames worked
now you got your wish

**Comment by chicken-nugget1104** [comment]
woops
it crashed on my end
lemme fix

**Comment by SaiyanGonzalez01** [comment]
does it work now?

**Comment by chicken-nugget1104** [comment]
it no longer crashes, yet i do not see the field

i do have a fix in mind

**Comment by SaiyanGonzalez01** [comment]
alright, hope it works!

**Comment by chicken-nugget1104** [comment]
> alright, hope it works!

it finally shows
its just behind the skin selector

**Comment by chicken-nugget1104** [comment]
finally hot-fixed, currently testing

**Comment by SaiyanGonzalez01** [comment]
nice! i'll take a little break of coding for the next few days since Thanksgiving is right around the corner.

**Comment by chicken-nugget1104** [comment]
> nice! i'll take a little break of coding for the next few days since Thanksgiving is right around the corner.

alr
i will still be here tho
doing stuff

i aint gonna take a break until thanksgiving day

**Comment by SaiyanGonzalez01** [comment]
You my friend are a committed coder, and I respect that! (Also is the username code working?)

**Comment by chicken-nugget1104** [comment]
> You my friend are a committed coder, and I respect that! (Also is the username code working?)

yep, finally about to commit

**Comment by chicken-nugget1104** [comment]
image
image

**Comment by SaiyanGonzalez01** [comment]
That looks better than the official username box XD

**Comment by chicken-nugget1104** [comment]
> That looks better than the official username box XD

commited!

**Comment by SaiyanGonzalez01** [comment]
Well, this will be the last merge i'll do for now. When I come back, I'll try to add some stuff aswell, don't want you just doing all the work.

**Comment by SaiyanGonzalez01** [comment]
mb xd

**Comment by chicken-nugget1104** [comment]
> Well, this will be the last merge i'll do for now. When I come back, I'll try to add some stuff aswell, don't want you just doing all the work.

heh k

**Comment by ghost** [comment]
You're calling profile.save on every keyboard update, that's only going to cause issues.

**Comment by chicken-nugget1104** [comment]
> You're calling profile.save on every keyboard update, that's only going to cause issues.

oh dang it

uh
ok i will fix this :sob:
just soon

im on a different computer RN

**Pull request merged**
